source('./process_data.R')
source('./plotting.R')
source('./gompertz.R')
setwd('../data/')

OD<-read.csv('./nissle_abs.csv',sep=',',header=TRUE)[2:101]
times<-t(read.csv('./nissle_abs.csv',sep=',',header=FALSE)[1,2:101])
names<-read.csv('./nissle_abs.csv',sep=',',header=TRUE)[1]

par(mfcol=c(2,2))
par(mar=c(5,5,4,1))
PlotCurve(log(OD[1:3,1:30]),times[1:30],'grey',c(0,300,-0.8,0.2),'yes','time after induction (mins)','ln(OD540)','PatoL')
PlotCurve(log(OD[4:6,1:30]),times[1:30],'pink',c(0,300,-0.8,0.2),'no','time after induction (mins)','ln(OD540)','PatoL')
legend('topleft',1,c('0mM acetoacetate','10mM acetoacetate'),col=c('black','red'),box.lty=0,bty='n',lty=1,lwd=2)
par(adj=0)
title('A)',cex.main=1.7)
par(adj=0.5)

#uninduced Gompertz fit patol high copy nissle
growth<-c()
value<-c(t(log(OD[1,1:30])),t(log(OD[2,1:30])),t(log(OD[3,1:30])))
level<-rep(c(times)[1:30],3)
growth<-data.frame(value,level)
colnames(growth)<-c('value','level')
dev<-tapply(growth$value,growth$level,sd)
growth$dev<-rep(dev,3)
startvalues<-c(0.005,0.5,60,-0.6)
mlefit<-MaxLikelihood(growth,startvalues)
chain<-run_metropolis_MCMC(mlefit,100000,growth$level,growth$value,growth$dev)
burnIn=10000
mcmcfit<-c(median(chain[-burnIn:-1,1]),median(chain[-burnIn:-1,2]),median(chain[-burnIn:-1,3]),median(chain[-burnIn:-1,4]))
x<-seq(min(growth$level),max(growth$level),0.1)
mq<-apply(chain[-burnIn:-1,],MARGIN=2,function(x){quantile(x,p=c(0.5))})
uq<-apply(chain[-burnIn:-1,],MARGIN=2,function(x){quantile(x,p=c(0.975))})
lq<-apply(chain[-burnIn:-1,],MARGIN=2,function(x){quantile(x,p=c(0.025))})
lines(x,Gompertz(mq,x),col='black',lty=1,lwd=1)
lines(x,Gompertz(lq,x),col='black',lty=2,lwd=1)
lines(x,Gompertz(uq,x),col='black',lty=2,lwd=1)
print(mcmcfit)
#induced Gompertz fit patol low copy nissle
growth<-c()
value<-c(t(log(OD[4,1:30])),t(log(OD[5,1:30])),t(log(OD[6,1:30])))
level<-rep(c(times)[1:30],3)
growth<-data.frame(value,level)
colnames(growth)<-c('value','level')
dev<-tapply(growth$value,growth$level,sd)
growth$dev<-rep(dev,3)
startvalues<-c(0.005,0.5,60,-0.6)
mlefit<-MaxLikelihood(growth,startvalues)
chain<-run_metropolis_MCMC(mlefit,100000,growth$level,growth$value,growth$dev)
burnIn=10000
mcmcfit<-c(median(chain[-burnIn:-1,1]),median(chain[-burnIn:-1,2]),median(chain[-burnIn:-1,3]),median(chain[-burnIn:-1,4]))
x<-seq(min(growth$level),max(growth$level),0.1)
mq<-apply(chain[-burnIn:-1,],MARGIN=2,function(x){quantile(x,p=c(0.5))})
uq<-apply(chain[-burnIn:-1,],MARGIN=2,function(x){quantile(x,p=c(0.975))})
lq<-apply(chain[-burnIn:-1,],MARGIN=2,function(x){quantile(x,p=c(0.025))})
lines(x,Gompertz(mq,x),col='red',lty=1,lwd=1)
lines(x,Gompertz(lq,x),col='red',lty=2,lwd=1)
lines(x,Gompertz(uq,x),col='red',lty=2,lwd=1)
print(mcmcfit)

par(new=FALSE)
PlotCurve(log(OD[7:9,1:30]),times[1:30],'grey',c(0,300,-0.8,0.2),'yes','time after induction (mins)','ln(OD540)','PatoL')
PlotCurve(log(OD[10:12,1:30]),times[1:30],'pink',c(0,300,-0.8,0.2),'no','time after induction (mins)','ln(OD540)','PatoL')
par(adj=0)
title('C)',cex.main=1.7)
par(adj=0.5)
legend('topleft',1,c('0mM acetoacetate','10mM acetoacetate'),col=c('black','red'),box.lty=0,bty='n',lty=1,lwd=2)

#uninduced Gompertz fit patol high copy nissle
growth<-c()
value<-c(t(log(OD[7,1:30])),t(log(OD[8,1:30])),t(log(OD[9,1:30])))
level<-rep(c(times)[1:30],3)
growth<-data.frame(value,level)
colnames(growth)<-c('value','level')
dev<-tapply(growth$value,growth$level,sd)
growth$dev<-rep(dev,3)
startvalues<-c(0.005,0.5,60,-0.6)
mlefit<-MaxLikelihood(growth,startvalues)
chain<-run_metropolis_MCMC(mlefit,100000,growth$level,growth$value,growth$dev)
burnIn=10000
mcmcfit<-c(median(chain[-burnIn:-1,1]),median(chain[-burnIn:-1,2]),median(chain[-burnIn:-1,3]),median(chain[-burnIn:-1,4]))
x<-seq(min(growth$level),max(growth$level),0.1)
mq<-apply(chain[-burnIn:-1,],MARGIN=2,function(x){quantile(x,p=c(0.5))})
uq<-apply(chain[-burnIn:-1,],MARGIN=2,function(x){quantile(x,p=c(0.975))})
lq<-apply(chain[-burnIn:-1,],MARGIN=2,function(x){quantile(x,p=c(0.025))})
lines(x,Gompertz(mq,x),col='black',lty=1,lwd=1)
lines(x,Gompertz(lq,x),col='black',lty=2,lwd=1)
lines(x,Gompertz(uq,x),col='black',lty=2,lwd=1)
print(mcmcfit)
#induced Gompertz fit patol low copy nissle
growth<-c()
value<-c(t(log(OD[10,1:30])),t(log(OD[11,1:30])),t(log(OD[12,1:30])))
level<-rep(c(times)[1:30],3)
growth<-data.frame(value,level)
colnames(growth)<-c('value','level')
dev<-tapply(growth$value,growth$level,sd)
growth$dev<-rep(dev,3)
startvalues<-c(0.005,0.5,20,-0.6)
mlefit<-MaxLikelihood(growth,startvalues)
chain<-run_metropolis_MCMC(mlefit,100000,growth$level,growth$value,growth$dev)
burnIn=10000
mcmcfit<-c(median(chain[-burnIn:-1,1]),median(chain[-burnIn:-1,2]),median(chain[-burnIn:-1,3]),median(chain[-burnIn:-1,4]))
x<-seq(min(growth$level),max(growth$level),0.1)
mq<-apply(chain[-burnIn:-1,],MARGIN=2,function(x){quantile(x,p=c(0.5))})
uq<-apply(chain[-burnIn:-1,],MARGIN=2,function(x){quantile(x,p=c(0.975))})
lq<-apply(chain[-burnIn:-1,],MARGIN=2,function(x){quantile(x,p=c(0.025))})
lines(x,Gompertz(mq,x),col='red',lty=1,lwd=1)
lines(x,Gompertz(lq,x),col='red',lty=2,lwd=1)
lines(x,Gompertz(uq,x),col='red',lty=2,lwd=1)
print(mcmcfit)

setwd('./nissle')
address=getwd()
data<-ProcessData(address)
medians<-GetMedians(data)
group='patol'
factor='acetoacetate'
PlotHist(data,group,factor,'mM',c(1.5,5,0,2),'none',c('black','red'))
mds=medians[medians$group==group & medians$level==0,]$median
points(mean(log10(mds)),2.0,col='grey',pch=20,cex=1.5)
segments(mean(log10(mds))-sd(log10(mds)),2.0,mean(log10(mds))+sd(log10(mds)),2.0,col='grey')
epsilon<-0.1
segments(mean(log10(mds))-sd(log10(mds)),2.0-epsilon,mean(log10(mds))-sd(log10(mds)),2.0+epsilon,col='grey')
segments(mean(log10(mds))+sd(log10(mds)),2.0-epsilon,mean(log10(mds))+sd(log10(mds)),2.0+epsilon,col='grey')
mds=medians[medians$group==group & medians$level==10,]$median
points(mean(log10(mds)),1.7,col='pink',pch=20,cex=1.5)
segments(mean(log10(mds))-sd(log10(mds)),1.7,mean(log10(mds))+sd(log10(mds)),1.7,col='pink')
epsilon<-0.1
segments(mean(log10(mds))-sd(log10(mds)),1.7-epsilon,mean(log10(mds))-sd(log10(mds)),1.7+epsilon,col='pink')
segments(mean(log10(mds))+sd(log10(mds)),1.7-epsilon,mean(log10(mds))+sd(log10(mds)),1.7+epsilon,col='pink')
par(adj=0)
title('B)',cex.main=1.7)
par(adj=0.5)
group='lpatol'
factor='acetoacetate'
PlotHist(data,group,factor,'mM',c(1.5,5,0,2),'none',c('black','red'))
mds=medians[medians$group==group & medians$level==0,]$median
points(mean(log10(mds)),2.0,col='grey',pch=20,cex=1.5)
segments(mean(log10(mds))-sd(log10(mds)),2.0,mean(log10(mds))+sd(log10(mds)),2.0,col='grey')
epsilon<-0.1
segments(mean(log10(mds))-sd(log10(mds)),2.0-epsilon,mean(log10(mds))-sd(log10(mds)),2.0+epsilon,col='grey')
segments(mean(log10(mds))+sd(log10(mds)),2.0-epsilon,mean(log10(mds))+sd(log10(mds)),2.0+epsilon,col='grey')
mds=medians[medians$group==group & medians$level==10,]$median
points(mean(log10(mds)),1.7,col='pink',pch=20,cex=1.5)
segments(mean(log10(mds))-sd(log10(mds)),1.7,mean(log10(mds))+sd(log10(mds)),1.7,col='pink')
epsilon<-0.1
segments(mean(log10(mds))-sd(log10(mds)),1.7-epsilon,mean(log10(mds))-sd(log10(mds)),1.7+epsilon,col='pink')
segments(mean(log10(mds))+sd(log10(mds)),1.7-epsilon,mean(log10(mds))+sd(log10(mds)),1.7+epsilon,col='pink')
par(adj=0)
title('D)',cex.main=1.7)
par(adj=0.5)
