source('./process_data.R')
source('./plotting.R')
source('./gompertz.R')
setwd('../data/')
OD<-read.csv('./dh5a_abs.csv',sep=',',header=TRUE)[2:101]
times<-t(read.csv('./dh5a_abs.csv',sep=',',header=FALSE)[1,2:101])
names<-read.csv('./dh5a_abs.csv',sep=',',header=TRUE)[1]
par(mfcol=c(2,2))
par(mar=c(4.5,5,3,1))

#scatterplot of growth curves patog
PlotCurve(log(OD[7:9,1:60]),times[1:60],'grey',c(0,600,-0.8,0),'yes','time after induction (mins)','ln(OD540)','PatoG')
PlotCurve(log(OD[10:12,1:60]),times[1:60],'pink',c(0,600,-0.8,0),'no','time after induction (mins)','ln(OD540)','PatoG')
#uninduced Gompertz fit patog
growth<-c()
value<-c(t(log(OD[7,1:60])),t(log(OD[8,1:60])),t(log(OD[9,1:60])))
level<-rep(c(times)[1:60],3)
growth<-data.frame(value,level)
colnames(growth)<-c('value','level')
dev<-tapply(growth$value,growth$level,sd)
growth$dev<-rep(dev,3)
startvalues<-c(0.001,0.5,60,-0.6)
mlefit<-MaxLikelihood(growth,startvalues)
chain<-run_metropolis_MCMC(mlefit,100000,growth$level,growth$value,growth$dev)
burnIn=10000
mcmcfit<-c(median(chain[-burnIn:-1,1]),median(chain[-burnIn:-1,2]),median(chain[-burnIn:-1,3]),median(chain[-burnIn:-1,4]))
x<-seq(min(growth$level),max(growth$level),0.1)
mq<-apply(chain[-burnIn:-1,],MARGIN=2,function(x){quantile(x,p=c(0.5))})
uq<-apply(chain[-burnIn:-1,],MARGIN=2,function(x){quantile(x,p=c(0.975))})
lq<-apply(chain[-burnIn:-1,],MARGIN=2,function(x){quantile(x,p=c(0.025))})
lines(x,Gompertz(mq,x),col='black',lty=1,lwd=1)
lines(x,Gompertz(lq,x),col='black',lty=2,lwd=1)
lines(x,Gompertz(uq,x),col='black',lty=2,lwd=1)
#induced Gompertz fit
growth<-c()
value<-c(t(log(OD[10,1:60])),t(log(OD[11,1:60])),t(log(OD[12,1:60])))
level<-rep(c(times)[1:60],3)
growth<-data.frame(value,level)
colnames(growth)<-c('value','level')
dev<-tapply(growth$value,growth$level,sd)
growth$dev<-rep(dev,3)
startvalues<-c(0.001,0.5,60,-0.6)
mlefit<-MaxLikelihood(growth,startvalues)
chain<-run_metropolis_MCMC(mlefit,100000,growth$level,growth$value,growth$dev)
burnIn=10000
mcmcfit<-c(median(chain[-burnIn:-1,1]),median(chain[-burnIn:-1,2]),median(chain[-burnIn:-1,3]),median(chain[-burnIn:-1,4]))
x<-seq(min(growth$level),max(growth$level),0.1)
mq<-apply(chain[-burnIn:-1,],MARGIN=2,function(x){quantile(x,p=c(0.5))})
uq<-apply(chain[-burnIn:-1,],MARGIN=2,function(x){quantile(x,p=c(0.975))})
lq<-apply(chain[-burnIn:-1,],MARGIN=2,function(x){quantile(x,p=c(0.025))})
lines(x,Gompertz(mq,x),col='red',lty=1,lwd=1)
lines(x,Gompertz(lq,x),col='red',lty=2,lwd=1)
lines(x,Gompertz(uq,x),col='red',lty=2,lwd=1)
legend('topleft',1,c('0mM acetoacetate','10mM acetoacetate'),col=c('black','red'),box.lty=0,bty='n',lty=c(1,1),lwd=2)
par(adj=0)
title('A)',cex.main=1.7)
par(adj=0.5)

#scatterplot of growth curves patol
PlotCurve(log(OD[25:27,1:60]),times[1:60],'grey',c(0,600,-0.2,0.5),'yes','time after induction (mins)','ln(OD540)','PatoL')
PlotCurve(log(OD[46:48,1:60]),times[1:60],'pink',c(0,600,-0.2,0.5),'no','time after induction (mins)','ln(OD540)','PatoL')
#uninduced Gompertz fit patol
growth<-c()
value<-c(t(log(OD[25,1:60])),t(log(OD[26,1:60])),t(log(OD[27,1:60])))
level<-rep(c(times)[1:60],3)
growth<-data.frame(value,level)
colnames(growth)<-c('value','level')
dev<-tapply(growth$value,growth$level,sd)
growth$dev<-rep(dev,3)
startvalues<-c(0.002,0.5,50,-0.15)
mlefit<-MaxLikelihood(growth,startvalues)
chain<-run_metropolis_MCMC(mlefit,100000,growth$level,growth$value,growth$dev)
burnIn=10000
mcmcfit<-c(median(chain[-burnIn:-1,1]),median(chain[-burnIn:-1,2]),median(chain[-burnIn:-1,3]),median(chain[-burnIn:-1,4]))
x<-seq(min(growth$level),max(growth$level),0.1)
mq<-apply(chain[-burnIn:-1,],MARGIN=2,function(x){quantile(x,p=c(0.5))})
uq<-apply(chain[-burnIn:-1,],MARGIN=2,function(x){quantile(x,p=c(0.975))})
lq<-apply(chain[-burnIn:-1,],MARGIN=2,function(x){quantile(x,p=c(0.025))})
lines(x,Gompertz(mq,x),col='black',lty=1,lwd=1)
lines(x,Gompertz(lq,x),col='black',lty=2,lwd=1)
lines(x,Gompertz(uq,x),col='black',lty=2,lwd=1)
#induced Gompertz fit
growth<-c()
value<-c(t(log(OD[46,1:60])),t(log(OD[47,1:60])),t(log(OD[48,1:60])))
level<-rep(c(times)[1:60],3)
growth<-data.frame(value,level)
colnames(growth)<-c('value','level')
dev<-tapply(growth$value,growth$level,sd)
growth$dev<-rep(dev,3)
startvalues<-c(0.002,0.5,50,-0.15)
mlefit<-MaxLikelihood(growth,startvalues)
chain<-run_metropolis_MCMC(mlefit,100000,growth$level,growth$value,growth$dev)
burnIn=10000
mcmcfit<-c(median(chain[-burnIn:-1,1]),median(chain[-burnIn:-1,2]),median(chain[-burnIn:-1,3]),median(chain[-burnIn:-1,4]))
x<-seq(min(growth$level),max(growth$level),0.1)
mq<-apply(chain[-burnIn:-1,],MARGIN=2,function(x){quantile(x,p=c(0.5))})
uq<-apply(chain[-burnIn:-1,],MARGIN=2,function(x){quantile(x,p=c(0.975))})
lq<-apply(chain[-burnIn:-1,],MARGIN=2,function(x){quantile(x,p=c(0.025))})
lines(x,Gompertz(mq,x),col='red',lty=1,lwd=1)
lines(x,Gompertz(lq,x),col='red',lty=2,lwd=1)
lines(x,Gompertz(uq,x),col='red',lty=2,lwd=1)
legend('topleft',1,c('0mM acetoacetate','10mM acetoacetate'),col=c('black','red'),box.lty=0,bty='n',lty=c(1,1),lwd=2)
par(adj=0)
title('C)',cex.main=1.7)
par(adj=0.5)
#plot patoG FACS
setwd('./facs')
address=getwd()
data<-ProcessData(address)
medians<-GetMedians(data)
group='patog'
PlotHist(data,group,'acetoacetate','mM',c(2,5,0,2.5),'none',c('black','red'))
mds=medians[medians$group==group & medians$level==0,]$median
points(mean(log10(mds)),2.5,col='grey',pch=20,cex=1.5)
segments(mean(log10(mds))-sd(log10(mds)),2.5,mean(log10(mds))+sd(log10(mds)),2.5,col='grey')
epsilon<-0.1
segments(mean(log10(mds))-sd(log10(mds)),2.5-epsilon,mean(log10(mds))-sd(log10(mds)),2.5+epsilon,col='grey')
segments(mean(log10(mds))+sd(log10(mds)),2.5-epsilon,mean(log10(mds))+sd(log10(mds)),2.5+epsilon,col='grey')
mds=medians[medians$group==group & medians$level==10,]$median
points(mean(log10(mds)),2,col='pink',pch=20,cex=1.5)
segments(mean(log10(mds))-sd(log10(mds)),2,mean(log10(mds))+sd(log10(mds)),2,col='pink')
epsilon<-0.1
segments(mean(log10(mds))-sd(log10(mds)),2-epsilon,mean(log10(mds))-sd(log10(mds)),2+epsilon,col='pink')
segments(mean(log10(mds))+sd(log10(mds)),2-epsilon,mean(log10(mds))+sd(log10(mds)),2+epsilon,col='pink')
par(new=FALSE)
par(adj=0)
title('B)',cex.main=1.7)
par(adj=0.5)
#plot patoL FACS
group='patol'
PlotHist(data,group,'acetoacetate','mM',c(2,5,0,2.5),'none',c('black','red'))
mds=medians[medians$group==group & medians$level==0,]$median
points(mean(log10(mds)),2.5,col='grey',pch=20,cex=1.5)
segments(mean(log10(mds))-sd(log10(mds)),2.5,mean(log10(mds))+sd(log10(mds)),2.5,col='grey')
epsilon<-0.1
segments(mean(log10(mds))-sd(log10(mds)),2.5-epsilon,mean(log10(mds))-sd(log10(mds)),2.5+epsilon,col='grey')
segments(mean(log10(mds))+sd(log10(mds)),2.5-epsilon,mean(log10(mds))+sd(log10(mds)),2.5+epsilon,col='grey')
mds=medians[medians$group==group & medians$level==10,]$median
points(mean(log10(mds)),2,col='pink',pch=20,cex=1.5)
segments(mean(log10(mds))-sd(log10(mds)),2,mean(log10(mds))+sd(log10(mds)),2,col='pink')
epsilon<-0.1
segments(mean(log10(mds))-sd(log10(mds)),2-epsilon,mean(log10(mds))-sd(log10(mds)),2+epsilon,col='pink')
segments(mean(log10(mds))+sd(log10(mds)),2-epsilon,mean(log10(mds))+sd(log10(mds)),2+epsilon,col='pink')
par(new=FALSE)
par(adj=0)
title('D)',cex.main=1.7)
par(adj=0.5)
setwd('../../R/')
