source('./process_data.R')
source('./plotting.R')
setwd('../data/time')
address=getwd()
data<-ProcessData(address)
group='patol'
factor='acetoacetate'
par(mar=c(5,5,4,1))
par(mfrow=c(1,2))
colors<-rev(topo.colors(14))
library(colorspace)
colors<-rev(sequential_hcl(14))
PlotHist(data,group,factor,'mM',c(1,5,0,1.5),'none',colors)
par(adj=0)
title('A)',cex=1.7)
par(adj=0.5)
legend('topleft',c('3 hours','16 hours'),col=c(colors[1],colors[14]),box.lty=0,bty='n',lty=1,cex=1,lwd=2)
par(new=FALSE)
group='lpatol'
PlotHist(data,group,factor,'mM',c(1,5,0,1.5),'none',colors)
par(adj=0)
title('B)',cex=1.7)
par(adj=0.5)
legend('topleft',c('3 hours','16 hours'),col=c(colors[1],colors[14]),box.lty=0,bty='n',lty=1,cex=1,lwd=2)
